### ISSUE TITLE
APIError: Code №214 - Access to adding post denied: access to the wall is closed

### ISSUE THREAD

**Issue by Konard** [Konard/vk-bot#36]
```
root@vds2441251:~/bots/vk-bot# node send-invitation-posts.js 
Post is sent to 195285978 community.
Post is sent to 34985835 community.
Post is sent to 24261502 community.
Post is sent to 53294903 community.
APIError: Code №214 - Access to adding post denied: access to the wall is closed
    at SequentialWorker.execute (/root/bots/vk-bot/node_modules/vk-io/lib/index.js:1664:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 214,
  params: [
    { key: 'method', value: 'wall.post' },
    { key: 'oauth', value: '1' },
    { key: 'v', value: '5.131' },
    { key: 'owner_id', value: '-8337923' },
    {
      key: 'message',
      value: 'Я программист.\n' +
        '\n' +
        'Принимаю все заявки в друзья.\n' +
        '\n' +
        'Ждать потребуется не более 10 минут.'
    }
  ],
  [cause]: undefined
}
root@vds2441251:~/bots/vk-bot# 
```

**Comment by Konard** [comment]
Fixed at https://github.com/Konard/vk-bot/commit/d1647269dea1e18869c2fb84816de504fc687716

**Comment by Konard** [comment]
```
root@vds2441251:~/bots/vk-bot# node send-invitation-posts.js
Post is sent to 195285978 community.
Post is sent to 34985835 community.
Post is sent to 24261502 community.
Post is sent to 53294903 community.
Post is sent to 33764742 community.
Post is sent to 94946045 community.
Post is sent to 39130136 community.
Post is sent to 194360448 community.
APIError: Code №214 - Access to adding post denied: access to the wall is closed
    at SequentialWorker.execute (/root/bots/vk-bot/node_modules/vk-io/lib/index.js:1664:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 214,
  params: [
    { key: 'method', value: 'wall.post' },
    { key: 'oauth', value: '1' },
    { key: 'v', value: '5.131' },
    { key: 'owner_id', value: '-198580397' },
    {
      key: 'message',
      value: 'Я программист.\n' +
        '\n' +
        'Принимаю все заявки в друзья.\n' +
        '\n' +
        'Ждать потребуется не более 10 минут.'
    }
  ],
  [cause]: undefined
}
root@vds2441251:~/bots/vk-bot# 
```

**Comment by Konard** [comment]
For some reason, error with `198580397` community is not reproducible. Maybe the wall was temporary closed and then was open again.
