### ISSUE TITLE
APIError: Code №10 - Internal server error

### ISSUE THREAD

**Issue by Konard** [Konard/vk-bot#67]
```
context.response {
  user_id: 707520792,
  message: 'С днём рождения! 💥\n' +
    '\n' +
    'Надеюсь, что твой день будет полон радости, а год впереди - прогресса и достижений. И чтобы помочь с этим, я подарю тебе ответ на любой вопрос по программированию и автоматизации.\n' +
    '\n' +
    'А ещё я могу подарить 1 рубль в связи с праздником на баланс мобильного телефона.',
  attachment: 'audio-2001064727_125064727',
  random_id: -3412275262732312
}
ticksPassed 0
/root/bots/vk-bot/node_modules/vk-io/lib/index.js:1664
            this.handleError(request, new APIError(response.error));
                                      ^

APIError: Code №10 - Internal server error
    at SequentialWorker.execute (/root/bots/vk-bot/node_modules/vk-io/lib/index.js:1664:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 10,
  params: [
    { key: 'method', value: 'messages.send' },
    { key: 'oauth', value: '1' },
    { key: 'v', value: '5.131' },
    { key: 'random_id', value: '-3412275262732312' },
    { key: 'user_id', value: '707520792' },
    { key: 'message', value: '*******' },
    { key: 'attachment', value: '*******' }
  ],
  [cause]: undefined
}

Node.js v18.18.2
root@vds2441251:~/bots/vk-bot# 
```

**Comment by Konard** [comment]
```
Greeting for friend 703221634 is added to queue.
greetedFriends: 30
{ 
  id: 703366422,
  track_code: 'bdabffc7TlNQJpLSWmv4O0USvYfbhm9mnxQN0SAY2ss5chGDXD0gNFd89ulVbag51j9rOR1CBBWLDQHGTnyplA',
  online: 0,
  first_name: 'Kobra',
  last_name: 'Ju',
  can_access_closed: true,
  is_closed: false
}
Loading conversations for 703366422 friend.
ticksPassed 1
ticksPassed 2
ticksPassed 3
ticksPassed 4
ticksPassed 5
ticksPassed 6
context.request { user_id: 703221634, sticker_id: 75306, random_id: -7597165252611483 }
context.response { user_id: 703221634, sticker_id: 75306, random_id: -7597165252611483 }
/root/bots/vk-bot/node_modules/vk-io/lib/index.js:1664
            this.handleError(request, new APIError(response.error));
                                      ^

APIError: Code №10 - Internal server error
    at SequentialWorker.execute (/root/bots/vk-bot/node_modules/vk-io/lib/index.js:1664:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 10,
  params: [
    { key: 'method', value: 'messages.send' },
    { key: 'oauth', value: '1' },
    { key: 'v', value: '5.131' },
    { key: 'random_id', value: '-7597165252611483' },
    { key: 'user_id', value: '703221634' },
    { key: 'sticker_id', value: '75306' }
  ],
  [cause]: undefined
}

Node.js v18.18.2
root@vds2441251:~/bots/vk-bot# 
```
