### ISSUE TITLE
APIError: Code №10 - Internal server error: could not check access_token now, check later.

### ISSUE THREAD

**Issue by Konard** [Konard/vk-bot#76]
```
APIError: Code №10 - Internal server error: could not check access_token now, check later.
    at SequentialWorker.execute (/root/bots/vk-bot/node_modules/vk-io/lib/index.js:1664:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 10,
  params: [
    { key: 'method', value: 'messages.getConversationsById' },
    { key: 'oauth', value: '1' },
    { key: 'v', value: '5.131' },
    { key: 'peer_ids', value: '723274787' },
    { key: 'count', value: '1' }
  ],
  [cause]: undefined
}
```

**Comment by ckieverentineas** [comment]
/home/vk-role-bot-magomir-central-bank/node_modules/vk-io/lib/index.js:1669
            this.handleError(request, new APIError(response.error));
****************************^
APIError: Code №10 - Internal server error: could not check access_token now, check later.
     at ParallelSelectedWorker.execute (/home/vk-role-bot-magomir-central-bank/node_modules/vk-io/lib/index.js:1669:39)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 10,
  params: [
    { key: 'method', value: 'docs.getMessagesUploadServer' },
    { key: 'oauth', value: '1' },
    { key: 'v', value: '5.131' },
    { key: 'type', value: 'doc' },
    { key: 'peer_id', value: '2000000001' }
  ],
  [cause]: undefined
}
